### ISSUE TITLE
Not work after update version - 0.1.9 to 0.2.5

### ISSUE THREAD

**Issue by RodrigoSMarques** [ChernyshenkoTaras/TCPickerView#24]
Hello,
I was using version 0.1.9 in an application that was in production. After requesting the update of the pods, it has been updated to version 0.2.5.

But my code does not work anymore and I noticed that it had several changes.

How can I solve?

![image](https://user-images.githubusercontent.com/17687286/42362443-a848ba02-80c9-11e8-98fd-acf67a8634bb.png)

I noticed that I can no longer use set only get.

var doneText: String { get }
var closeText: String { get }

var backgroundColor: UIColor { get }
var titleColor: UIColor { get }
var doneTextColor: UIColor { get }
var closeTextColor: UIColor { get }
var headerBackgroundColor: UIColor { get }
var doneBackgroundColor: UIColor { get }
var closeBackgroundColor: UIColor { get }
var separatorColor: UIColor { get }

var buttonsFont: UIFont { get }
var titleFont: UIFont { get }

var rowHeight: CGFloat { get }
var headerHeight: CGFloat { get }
var cornerRadius: CGFloat { get }

**Comment by ChernyshenkoTaras** [comment]
Hi,
First of all, thank you for interesting in my library. It's important to know that people using it :)

About your issue:

I've changed library API for better user experience. Before you was needed to update UI for each picker you have in a project. So if you would have picker in 3 places, for example, you were needed to write same code for UI for each picker. It was leading to code duplication in project.

That's why I decide to move all code which is related to UI appearance into one place that could be reused around the project. I called it `Theme` and you can find protocol `TCPickerViewThemeType` which is describes all properties which could be customized.

So, right now you have two options to resolve your issue:

1) Specify pod version in you `Podfile`, like `pod 'TCPickerView', '~>0.1.9` so you will use old API and you will not need any changes in your project

2) Use new API. What you will need to Dom it's subclass `TCPickerViewThemeType` protocol and customize needed properties. For more info you can refer to `TCPickerViewDefaultTheme` class.

**Comment by rodrigosmarques** [comment]
Hello,
I did not understand how to use protocols to customize the UI.
I made a few attempts and could not.
Can you show me an example? Customize the colors and title of the buttons?

**Comment by RodrigoSMarques** [comment]
Thanks, I was able to make the changes and I'm working on the new version.

Her library is very good, she spared me a great job.

**Comment by ChernyshenkoTaras** [comment]
I'm glad that you figure it out and thanks for warm words. I will close this issue now, but if you will have additional questions feel free to reopen this one or create new issue.
