### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by ShehrozArif** [ChernyshenkoTaras/TCPickerView#31]
Can you please add search functionality in picker.

**Comment by ChernyshenkoTaras** [comment]
Hey @ShehrozArif! 

Sorry that it took so long, but finally I was able to make small improvements to this library and added search functionality. In order to use the search, you will need to get the updated library version(0.2.8) and then follow the instructions in the readme.

I will close this issue, but feel free to reopen it if you will find any issues related to the search functionality.
