### ISSUE TITLE
No such module 'TCPickerView'

### ISSUE THREAD

**Issue by Neeraj204** [ChernyshenkoTaras/TCPickerView#7]
No such module 'TCPickerView' either by using pod or drag-n-drop method

**Comment by ChernyshenkoTaras** [comment]
Hi @Neeraj204 ,
I'm glad what you are interested in this library, so let's try to resolve your issues.
- First of all, when you drag-n-drop library into your project, u DON'T need to import TCPickerView manual. You didn't do that, right?
- In second, when you use it thru cocoapods, you need to open file with .xcworkspace extension instead of .xcodeproj. Could you confirm you did it? 

Please, let me know if it will help or not

**Comment by Neeraj204** [comment]
Thanks for the quick reply. I did all the steps you mentioned. What worked for me is to include Classes file into project build phases >> Compile Sources.

**Comment by ChernyshenkoTaras** [comment]
You did it when you manually add files, right?
But when you add it thru cocoa pods, if it appear at Pods folder of your project?

**Comment by Neeraj204** [comment]
Yes did it by manual, nothing appears in folder when using pods except .plist file.

**Comment by ChernyshenkoTaras** [comment]
try to make `pod repo update` and then `pod install`

**Comment by Neeraj204** [comment]
Well I did using Drag and drop method, and again thanks for the great library mate..!!
